services:
  postgres:
    image: postgres:16-alpine
    container_name: uaikifome-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: uaikifome
      POSTGRES_PASSWORD: uaikifome123
      POSTGRES_DB: uaikifome
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: uaikifome-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitmqdata:
