services:
  postgres:
    image: postgres:16-alpine
    container_name: uaikifome-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: uaikifome
      POSTGRES_PASSWORD: uaikifome123
      POSTGRES_DB: uaikifome
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
